### ISSUE TITLE
Between a Rock Displaying wrong Item Requirements

### ISSUE THREAD

**Issue by Lungerx** [Zoinkwiz/quest-helper#1397] opened 2024-01-20 01:52 UTC
Between a Rock is displaying that the quest requires 27012 Ammo moulds instead of just 1. 
![error](https://github.com/Zoinkwiz/quest-helper/assets/148188130/e0127c36-6086-4050-aa81-43e6fe7792d7)

**Comment by pajlada** [comment] 2024-01-20 07:43
Duplicate of #1389, which was fixed in #1390 
Will be part of the next release which is waiting to be merged in https://github.com/runelite/plugin-hub/pull/5404

**Closed** 2024-01-21 10:59 UTC
