### ISSUE TITLE
The Giant Dwarf missing step

### ISSUE THREAD

**Issue by Xalthox** [Zoinkwiz/quest-helper#1331] opened 2023-11-12 21:12 UTC
After talking to Blasidar the sculptor. The step where we have to talk to Vermundi the first time, so he can let us know to meet the librarian for a book. The book has the knowledge of how the kings  clothes look. That whole set is missing and after talking to Blasidar the sculptor, the next step goes straight to trying to use the coil on the silk machine to fix it, which is wrong.

**Comment by Zoinkwiz** [comment] 2024-02-24 13:16
Duplicate of #223

**Closed by Zoinkwiz** 2024-02-24 13:16 UTC
Labels: bug, duplicate
