### ISSUE TITLE
Remove all favour requirements

### ISSUE THREAD

**Issue by 20k-ultra** [Zoinkwiz/quest-helper#1398] opened 2024-01-20 23:07 UTC
Favour system was removed January 10th, 2024 so they are no longer needed for all quests

https://oldschool.runescape.wiki/w/Update:Children_of_the_Sun#Kourend_Changes

**Comment by pajlada** [comment] 2024-01-21 10:35
Duplicate of #1394 - fixed in the version that's currently being reviewed for release.

**Closed** 2024-01-21 10:59 UTC
