### ISSUE TITLE
Morytania hard diary gets bugged (after Salve shortcut step)

### ISSUE THREAD

**Issue by Scape070** [Zoinkwiz/quest-helper#599] opened 2021-12-09 18:46 UTC
The plugin doesn't count completing the diary step "Use the shortcut to get to the bridge over the Salve" and gets stuck. Even if you open and close the diary menu, log in and out of game, or disable/enable the plugin, it still stays stuck there.

![2021-12-09_19-35-23](https://user-images.githubusercontent.com/95359977/145455889-a81441d4-59c6-4524-ad46-36c7c7c902e9.png)

**Comment by Kerpackie** [comment] 2021-12-09 22:35
Duplicate of #596 Currently working on resolving this!

**Closed** 2021-12-10 10:27 UTC
