### ISSUE TITLE
Mournings End Part 2

### ISSUE THREAD

**Issue by ChrisWPG** [Zoinkwiz/quest-helper#482] opened 2021-10-12 01:35 UTC
On puzzle 5 the overlay does not tell you to put the blue crystal in the blue room. Once the blue crystal is placed there is no reminder to take the mirror out at the entrance and there is also no reminder to take the yellow crystal out on the way up north.

**Comment by robert-clayton** [comment] 2021-10-17 23:17
Not sure if this was resolved in the interim, but I just did this quest earlier today and the plugin seemed to point everything out correctly for me 🤔

**Comment by Zoinkwiz** [comment] 2021-12-11 22:34
Duplicate of https://github.com/Zoinkwiz/quest-helper/issues/161

**Closed by Zoinkwiz** 2021-12-11 22:34 UTC
