### ISSUE TITLE
Incorrect ItemRequirement constructor used for cannon mould

### ISSUE THREAD

**Issue by aemsle** [Zoinkwiz/quest-helper#1396] opened 2024-01-19 09:43 UTC
the item requirments for "Between a Rock..." says 27012 Ammo moulds are required.

It seems like two itemIDs were passed onto ItemRequirement:
![image](https://github.com/Zoinkwiz/quest-helper/assets/44575716/1fe01332-ba83-4a6f-92d4-93ab3d03f78f)

 which caused this constructor to be called : 
![image](https://github.com/Zoinkwiz/quest-helper/assets/44575716/ffdaae0d-b666-478a-8952-252ad9a02749)

instead of: 
![image](https://github.com/Zoinkwiz/quest-helper/assets/44575716/6918f473-7a3c-44e6-a1c3-f5e3c4853945)

possible fix could be to add: 
![image](https://github.com/Zoinkwiz/quest-helper/assets/44575716/444f4e14-8a8f-47f1-ac67-cc9d79ce180a)

to ItemCollections.java? I would make a PR myself but im not very comfortable with java/the build system being used so il let maintainers decide the best course.

EDIT: forgot to add current behaviour screenshot:
![image](https://github.com/Zoinkwiz/quest-helper/assets/44575716/5e631138-9dfe-4f8f-aef7-221048f0718a)

**Comment by pajlada** [comment] 2024-01-19 10:11
Duplicate of #1389, which was fixed in #1390 
Will be part of the next release which is waiting to be merged in https://github.com/runelite/plugin-hub/pull/5404

Thank you for reporting it & looking into it so thoroughly!

**Closed** 2024-01-21 10:59 UTC
