### ISSUE TITLE
Merlin's Crystal small bug

### ISSUE THREAD

**Issue by tre3tre** [Zoinkwiz/quest-helper#499] opened 2021-10-15 20:55 UTC
During "Get Excalibur" talking to the lady of the lake doesn't trigger the next step and keeps prompting you to talk to her instead of going to port sarim.

**Comment by Zoinkwiz** [comment] 2021-12-11 22:17
Duplicate of https://github.com/Zoinkwiz/quest-helper/issues/425

**Closed by Zoinkwiz** 2021-12-11 22:17 UTC
Labels: bug
