### ISSUE TITLE
(Minor issue) Wrong amount of ammo mould's listed in required items for "Between a rock.."

### ISSUE THREAD

**Issue by MousePrincess** [Zoinkwiz/quest-helper#1400] opened 2024-01-26 04:29 UTC
![image](https://github.com/Zoinkwiz/quest-helper/assets/101374834/2b2b65da-246f-421b-a08b-19c495d1b434)

Quest helper lists it as needing "27012" Ammo mould's, which is the item ID for double ammo mould. I assume it is meant to say "1 ammo mould or double ammo mould".

**Comment by pajlada** [comment] 2024-01-26 13:42
Duplicate of #1389, which was fixed in #1390 
Will be part of the next release which is waiting to be merged in https://github.com/runelite/plugin-hub/pull/5404

**Closed** 2024-02-24 08:09 UTC
