### ISSUE TITLE
Mourning's End Part II

### ISSUE THREAD

**Issue by sgovaerts** [Zoinkwiz/quest-helper#222] opened 2021-02-13 14:45 UTC
In the puzzle 5 p1 ending, I got stuck on the Put a mirror in the pillar to the south and point it to east. For some reason it kept jumping to part 2 without me having pointed the mirror east and placing the blue crystal in the pillar. Was quite confusing till I just read the next task in the description instead of the top left quest helper part.
Since I didn't place the blue crystal yet, you can't finish part 2 and it just mentions to try to start over.

**Comment by Zoinkwiz** [comment] 2021-12-11 22:35
Duplicate of https://github.com/Zoinkwiz/quest-helper/issues/161

**Closed by Zoinkwiz** 2021-12-11 22:35 UTC
