### ISSUE TITLE
The Giant Dwarf dialogue with Reldo and librarian bug

### ISSUE THREAD

**Issue by ccarpenter49er** [Zoinkwiz/quest-helper#821] opened 2022-06-19 21:49 UTC
I'm on the step of the quest where you must talk to the librarian about the Imcando Dwarves. There is no option to do that and so I went to Reldo in Varrock and there is also no option for this dialogue. I have tried re-logging and opening the quest diary multiple times. Please help.

**Comment by Zoinkwiz** [comment] 2024-02-24 13:16
Duplicate of #223

**Closed by Zoinkwiz** 2024-02-24 13:16 UTC
